### ISSUE TITLE
Mortar lags

### ISSUE THREAD

**Issue by FoviOX** [VolmitSoftware/Gloss#89]
**Describe the bug**
Mortar lagging. I found this when open player list. On server playing 43 players.

**Screenshots or Video Recordings**
https://youtu.be/cqNpdnoOzZw

**Server and Plugin Informations**
 - Gloss and Mortar Version: 1.3.2, 1.0.71
 - Server Platform and Version: Spigot 1.12.1

**Additional context**
![mortar](https://user-images.githubusercontent.com/33469628/63428139-7bb4fd80-c41f-11e9-803f-e9ec0e5123e2.jpg)
![image](https://user-images.githubusercontent.com/33469628/63428172-8ff8fa80-c41f-11e9-88ea-9d669e9f1110.png)

**Comment by DavidRockin** [comment]
It's not mortar lagging. I'm having some troubles trying to reproduce this issue.

Can you see if you can try to alter your config to have a lower rate and send less packets?

```yaml
  boards:
    max-packets-per-second: 140
    target-update-rate: 48
  tablist:
    max-packets-per-second: 120
    target-update-rate: 29
```

If you can message me on Discord, I can guide you through profiling your server. However it'll require you to be online and available for up to a few hours.
